# Configuration for Compose, see https://detekt.dev/docs/introduction/compose/
style:
  MaxLineLength:
    maxLineLength: 150
    excludes: [ '**/test/**', '**/*.Test.kt' ]
  ReturnCount:
    max: 5
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
  UnusedPrivateMember:
    ignoreAnnotated: [ 'Preview' ]

naming:
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'

complexity:
  LongParameterList:
    constructorThreshold: 15
    ignoreDefaultParameters: true
  LongMethod:
    threshold: 80
  TooManyFunctions:
    thresholdInFiles: 16
    thresholdInInterfaces: 16
    ignorePrivate: true
    ignoreAnnotatedFunctions: [ 'Preview' ]
    thresholdInClasses: 15
  ComplexCondition:
    threshold: 10
